# Generated by Django 4.2.20 on 2025-04-19 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0004_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='airhall_image',
            field=models.ImageField(blank=True, null=True, upload_to='airhall_items/'),
        ),
        migrations.AddField(
            model_name='item',
            name='airhall_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_in_airhall',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
