# Generated by Django 4.2.20 on 2025-04-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('electronics', 'Electronics'), ('home', 'Home & Garden'), ('sports', 'Sports & Outdoors'), ('toys', 'Toys & Games'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
