# Generated by Django 4.2.20 on 2025-04-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_category_item_views_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('clothes', 'Одежда'), ('shoes', 'Обувь'), ('grip', 'Средства для сцепления'), ('other', 'Другое')], default='other', max_length=100),
        ),
    ]
