# Generated by Django 4.2.20 on 2025-04-21 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0010_item_banned_at_item_banned_by_item_banned_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='banned_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='banned_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='banned_reason',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_banned',
        ),
        migrations.AlterField(
            model_name='item',
            name='airhall_image',
            field=models.ImageField(blank=True, null=True, upload_to='airhall_items/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
