# Generated by Django 4.2.20 on 2025-04-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_remove_item_banned_at_remove_item_banned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
